# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 30 Nov 2018 07:00:42 +0000
*               @ALL          1
*               @user         8
