<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: yzs
 * Date: Sun, 02 Dec 2018 14:09:32 +0800
 */

$conf['title'] = '無為自然農園';
$conf['start'] = 'welcome';
$conf['lang'] = 'zh';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'yzs';
$conf['proxy']['pass'] = '<b>MTIzNDU2QEU=';

// end auto-generated content
